module.exports = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  CLEAR_CURRENT_USER: 'CLEAR_CURRENT_USER',
  LOADING_USER_INFO: 'LOADING_USER_INFO',
  CHANGE_PROFILE_USER: 'CHANGE_PROFILE_USER',
  CHANGE_SETTING_USER: 'CHANGE_SETTING_USER',
  FETCH_PERMISSIONS_SUCCESS: 'FETCH_PERMISSIONS_SUCCESS',
  FETCHING_APPROVAL_PROCESS_FAILURE: 'FETCHING_APPROVAL_PROCESS_FAILURE',
  FETCH_SETTING: 'FETCHING_SETTING',
  FETCH_SETTING_SUCCESS: 'FETCH_SETTING_SUCCESS',
  FETCH_SETTING_FAILURE: 'FETCH_SETTING_FAILURE'
};